### ISSUE TITLE
Do I need dependencies on destination Windows PC?

### ISSUE THREAD

**Issue by frederikhors** [adrg/go-wkhtmltopdf#10]
If I compile for Windows my Golang project can I use the executable on another machine without `wkhtmltopdf/wkhtmltox` dependencies installed on that machine?

**Comment by adrg** [comment]
Hi @frederikhors. No, you don't have to install `wkhtmltox` if you want to run your executable on other machines. However, you will need to ship your application with `wkhtmltox.dll`. As long as your executable and the DLL file are in the same directory, you should be able to run your application.
