### ISSUE TITLE
Prerequisites Install Error

### ISSUE THREAD

**Issue by xizaidqm** [adrg/go-wkhtmltopdf#13]
Hello

When I followed [this instruction](https://github.com/adrg/go-wkhtmltopdf/issues/9) to install wkhtmltox in my Windows, some errors occured.

1. I chose to install wkhtmltopdf in E:\wkhtmltox. 
![image](https://user-images.githubusercontent.com/26849307/131708486-543e2e7c-8f57-4a10-8d87-131fa7de62c0.png)

When I tried to use "go build" in cmd, I got the message as follows.  It said "package .: no Go files in E:\wkhtmltox". **How can I solve this problem?**

![image](https://user-images.githubusercontent.com/26849307/131708038-17b54fdc-0302-412e-9094-e711264aa014.png)

2. Another issue may associate with the first problem. 

Although I "go build" failed,  I still tried to run my program. Unfortunately, it did not work and gave me some error messages. How can I solve with it?

Please Help me! Thank you! 

![image](https://user-images.githubusercontent.com/26849307/131709281-d8252838-c4b3-40a4-9af2-8ca218781156.png)

**Comment by adrg** [comment]
Hi @xizaidqm.

The idea is to inform Go about the location of the `wkhtmltox` SDK files prior to building your application, in the same environment. 
```bash
set CGO_LDFLAGS=-LE:\wkhtmltox\bin
set CGO_CFLAGS=-IE:\wkhtmltox\include
```
So in your case, one solution would be running the commands above in the terminal if your IDE/editor (I'm not sure what you are using) prior to doing `go build main.go`.

Another solution would be to build your application from a Windows `cmd` instance. So you would open a `cmd` instance in the location you have your project (where you have your `main.go` file) and run the commands there: 
```bash
set CGO_LDFLAGS=-LE:\wkhtmltox\bin
set CGO_CFLAGS=-IE:\wkhtmltox\include
go build main.go
```

Also, I see you are getting some `C` errors when trying to build your application. You might need to install the `MinGW toolchain`. Please see https://github.com/adrg/go-wkhtmltopdf/wiki/Install-MinGW-toolchain for that.

**Comment by xizaidqm** [comment]
Hello @adrg ! Thanks for your quick support!

I followed your advise and install suitable MinGW. Now I can build my program and generate main.exe.

However, when I run main.exe, it seems does not work. When I tried to convert html file to corresponding PDF file, the PDF file is 0KB, and I can not even open it. (content.html is the source file, content.pdf is generated by running main.exe)
![image](https://user-images.githubusercontent.com/26849307/132092936-e00d80c2-fc9e-47e0-b012-477fd27c8ea8.png)

My source code is as followed.
![image](https://user-images.githubusercontent.com/26849307/132093115-ba695b70-74eb-4a0c-9248-dff77375a217.png)

In the picture above, "filePath" is the absolute path of content.html, "outputPath" is  the absolute path of content.pdf.

How can I solve this problem? Is this my code fault or something else?

**Comment by adrg** [comment]
Hi @xizaidqm. I think you forgot to do (at least I don't see it in the picture you attached):

```go
converter.Add(object)
```

You need to add the objects you create to the converter (before doing `converter.Run()`) in order for them to be added to the output PDF file.

Let me know if that solves your issue.

**Comment by xizaidqm** [comment]
Thank you for your kind answer.

I have solved my issues and now I can generate PDF file successfully by running main.exe.

**Comment by adrg** [comment]
Glad to hear you solved the problem you were having. Please close this issue if everything is sorted out.
