### ISSUE TITLE
Blank pdf for react website.

### ISSUE THREAD

**Issue by anoop012345** [adrg/go-wkhtmltopdf#22]
I am trying to save a page from my site built in react. It generate the blank pdf as site is take sometime to load. 
Is there any way to fix this issue?

**Comment by adrg** [comment]
Hi @anoop012345. Is your website public by any chance so I can test the conversion?

Does it work if you use the `wkhtmltopdf` binary directly? If it doesn't, then there's not much I can do about it, as this package uses the `wkhtmltox` library, the same as the binary.

```bash
wkhtmltopdf https://yourwebsite.com out.pdf
```

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if there are any issues with the provided solution.
