### ISSUE TITLE
html website need token in header , how can i config ?

### ISSUE THREAD

**Issue by aveyuan** [adrg/go-wkhtmltopdf#23]
Hi, I hava a html website need token in header , how can i set ? Thanks

**Comment by adrg** [comment]
Hi @aveyuan. I'm sorry, I don't understand your question. Can you provide more details regarding what you are trying to achieve?

If you need to add some content in the header/footer, you can use the `ContentLeft`, `ContentCenter` and `ContentRight` fields of the [Header](https://github.com/adrg/go-wkhtmltopdf/blob/master/object.go#L55) struct. Please see the [basic usage example](https://github.com/adrg/go-wkhtmltopdf/blob/master/examples/basic-usage/main.go#L22).

**Comment by aveyuan** [comment]
> 嗨@aveyuan。对不起，我不明白你的问题。您能否提供有关您要实现的目标的更多详细信息？
> 
> 如果需要在页眉/页脚中添加一些内容，可以使用[Header](https://github.com/adrg/go-wkhtmltopdf/blob/master/object.go#L55)结构的`ContentLeft`,`ContentCenter`和`ContentRight`字段。请参阅[基本用法示例](https://github.com/adrg/go-wkhtmltopdf/blob/master/examples/basic-usage/main.go#L22)。[](https://github.com/adrg/go-wkhtmltopdf/blob/master/object.go#L55)[](https://github.com/adrg/go-wkhtmltopdf/blob/master/examples/basic-usage/main.go#L22)

Thanks reply, 
```
pdf.NewObject("http://domain.com/xxx.html")
```
The object is URL, URL need customer Header like  jwt token.

**Comment by aveyuan** [comment]
http header not pdf header.

**Comment by adrg** [comment]
Oh, I see. There is no way to do that currently. I did some quick research and found that there are some undocumented options for setting custom headers in the `wkhtmltox` [object documentation](https://wkhtmltopdf.org/libwkhtmltox/pagesettings.html#pagePdfObject):
```
load.customHeaders TODO
load.repertCustomHeaders Should the custom headers be sent all elements loaded instead of only the main page? Must be either "true" or "false".
```

I'm not sure if they work or not. I will test them when I get a bit of time and add them to the package if they work properly.

**Comment by aveyuan** [comment]
> 哦，我明白了。目前没有办法做到这一点。我做了一些快速研究，发现在`wkhtmltox` [对象文档](https://wkhtmltopdf.org/libwkhtmltox/pagesettings.html#pagePdfObject)中设置自定义标头有一些未记录的选项：
> 
> ```
> load.customHeaders TODO
> load.repertCustomHeaders Should the custom headers be sent all elements loaded instead of only the main page? Must be either "true" or "false".
> ```
> 
> 我不确定它们是否有效。当我有时间时，我会测试它们，如果它们正常工作，我会将它们添加到包中。

I find `pdf.NewObjectFromReader()` method, I can use  go package `net/http`  Request(Get/Post....) solve.Thanks

**Comment by adrg** [comment]
> I find `pdf.NewObjectFromReader()` method, I can use go package `net/http` Request(Get/Post....) solve.Thanks

Yeah, you can use a custom HTTP client, retrieve the HTML content yourself and pass it to the `pdf.NewObjectFromReader` function. I was going to suggest that as well as a workaround.

I'll leave some sample code here for other users of the library who might find this thread useful.
```go
package main

import (
	"log"
	"net/http"
	"os"

	pdf "github.com/adrg/go-wkhtmltopdf"
)

func main() {
	// Make HTTP request.
	client := http.Client{}

	req, err := http.NewRequest("GET", "https://example.com", nil)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Authorization", "Bearer Token")

	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	// Initialize library.
	if err := pdf.Init(); err != nil {
		log.Fatal(err)
	}
	defer pdf.Destroy()

	// Create object from reader.
	object, err := pdf.NewObjectFromReader(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	object.LoadImages = true

	// Create converter.
	converter, err := pdf.NewConverter()
	if err != nil {
		log.Fatal(err)
	}
	defer converter.Destroy()

	// Add created objects to the converter.
	converter.Add(object)

	// Convert objects and save the output PDF document.
	outFile, err := os.Create("out.pdf")
	if err != nil {
		log.Fatal(err)
	}
	defer outFile.Close()

	if err := converter.Run(outFile); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by aveyuan** [comment]
> > I find `pdf.NewObjectFromReader()` method, I can use go package `net/http` Request(Get/Post....) solve.Thanks
> 
> Yeah, you can use a custom HTTP client, retrieve the HTML content yourself and pass it to the `pdf.NewObjectFromReader` function. I was going to suggest that as well as a workaround.
> 
> I'll leave some sample code here for other users of the library who might find this thread useful.
> 
> ```go
> package main
> 
> import (
> 	"log"
> 	"net/http"
> 	"os"
> 
> 	pdf "github.com/adrg/go-wkhtmltopdf"
> )
> 
> func main() {
> 	// Make HTTP request.
> 	client := http.Client{}
> 
> 	req, err := http.NewRequest("GET", "https://example.com", nil)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	req.Header.Set("Authorization", "Bearer Token")
> 
> 	resp, err := client.Do(req)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer resp.Body.Close()
> 
> 	// Initialize library.
> 	if err := pdf.Init(); err != nil {
> 		log.Fatal(err)
> 	}
> 	defer pdf.Destroy()
> 
> 	// Create object from reader.
> 	object, err := pdf.NewObjectFromReader(resp.Body)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	object.LoadImages = true
> 
> 	// Create converter.
> 	converter, err := pdf.NewConverter()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer converter.Destroy()
> 
> 	// Add created objects to the converter.
> 	converter.Add(object)
> 
> 	// Convert objects and save the output PDF document.
> 	outFile, err := os.Create("out.pdf")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer outFile.Close()
> 
> 	if err := converter.Run(outFile); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```

Great, you can add to examples
