### ISSUE TITLE
WARNING: QApplication was not created in the main() thread.

### ISSUE THREAD

**Issue by yuanshanhshan** [adrg/go-wkhtmltopdf#28]
can not use as a function 
WARNING: QApplication was not created in the main() thread.

**Comment by adrg** [comment]
Hi @yuanshanhshan. This is a known limitation of `wkhtmltox`, not of this package. The library must be initialized on the main thread and the conversion must be performed on the main thread as well. See my [HTTP server example](https://github.com/adrg/go-wkhtmltopdf/tree/master/examples/http-server) for more information.

**Comment by yuanshanhshan** [comment]
Thanks for your help.
