### ISSUE TITLE
wkhtmltopdf is deprecated by its author.

### ISSUE THREAD

**Issue by karelbilek** [adrg/go-wkhtmltopdf#30]
wkhtmltopdf is deprecated by its author and is no longer maintained.

I think it should be at least mentioned here.

**Comment by adrg** [comment]
Hi @karelbilek,

Sure, I added a note mentioning the project status of `wkhtmltopdf` (and implicitly `wkhtmltox`) in the [README.md](https://github.com/adrg/go-wkhtmltopdf#prerequisites) file.

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if necessary.
