### ISSUE TITLE
需要C包的支持

### ISSUE THREAD

**Issue by tobytoby** [adrg/go-wkhtmltopdf#34]
mac环境下golang1.18报错：
# github.com/adrg/go-wkhtmltopdf
../../../../pkg/mod/github.com/adrg/go-wkhtmltopdf@v0.3.0/converter.go:7:10: fatal error: 'wkhtmltox/pdf.h' file not found
#include <wkhtmltox/pdf.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

**Comment by feyounger** [comment]
I also noticed this issue, which should be that there is no corresponding C package on Mac.

**Comment by feyounger** [comment]
从wkhtmltopdf这个工具的发布时间来看，作者并没有支持mac的M系列版本，只支持了x86
