### ISSUE TITLE
Creating PDF files in a loop

### ISSUE THREAD

**Issue by zaky** [adrg/go-wkhtmltopdf#38]
func main() {
	for _, v := range []string{"import1.pdf", "import2.pdf", "import3.pdf"} {
		CreatePDFFile("header.html", "footer.html", "content.html", v)
	}
}

func CreatePDFFile(header, footer, content, output string) error {
	// Initialize library.
	if err := pdf.Init(); err != nil {
		log.Print("fail init", err)

		return err
	}
	defer pdf.Destroy()
	//Insert the content inside the template
	// Create object from URL.
	object, err := pdf.NewObject(content)
	if err != nil {
		log.Print("fail new object", err)
		return err
	}
	defer object.Destroy()
	object.Header.CustomLocation = header
	object.Footer.CustomLocation = footer
	converter, err = pdf.NewConverter()
	if err != nil {
		log.Print("fail new converter", err)
		return err
	}

	defer converter.Destroy()

	converter.PaperSize = pdf.Letter

	// Add created objects to the converter.
	converter.Add(object)

	// Convert objects and save the output PDF document.
	outFile, err := os.Create(output)
	if err != nil {
		log.Print("fail create", err)
		return err
	}
	defer outFile.Close()

	// Run converter.
	if err := converter.Run(outFile); err != nil {
		log.Print("fail run", err)
		return err
	}
	return nil
}

Runing this code will create 1 valid file, the first one and two invalid files.

**Comment by adrg** [comment]
Hi @zaky

The library needs to be initialized only once, when the application starts. This should work fine:

```go
package main

import (
	"log"
	"os"

	pdf "github.com/adrg/go-wkhtmltopdf"
)

func main() {
	// Initialize library.
	if err := pdf.Init(); err != nil {
		log.Fatal(err)
	}
	defer pdf.Destroy()

	for _, v := range []string{"import1.pdf", "import2.pdf", "import3.pdf"} {
		if err := CreatePDFFile("header.html", "footer.html", "content.html", v); err != nil {
			log.Fatal(err)
		}
	}
}

func CreatePDFFile(header, footer, content, output string) error {
	// Create object from URLs.
	object, err := pdf.NewObject(content)
	if err != nil {
		return err
	}
	defer object.Destroy()

	object.Header.CustomLocation = header
	object.Footer.CustomLocation = footer

	// Create converter.
	converter, err := pdf.NewConverter()
	if err != nil {
		return err
	}
	defer converter.Destroy()

	converter.PaperSize = pdf.Letter

	// Add created objects to the converter.
	converter.Add(object)

	// Convert objects and save the output PDF document.
	outFile, err := os.Create(output)
	if err != nil {
		return err
	}
	defer outFile.Close()

	// Run converter.
	if err := converter.Run(outFile); err != nil {
		return err
	}

	return nil
}
```

**Comment by zaky** [comment]
Actually the code is part of a web server.
What I fount is that if I put the pdf.init/pdf.destroy in main the first request is working fine but the the following requests.
If I put the init/destroy in the handler its working fine.
I dont undersatnd why.

Anyway from the second requests and on I get 
```
WARNING: QApplication was not created in the main() thread.
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
QObject::startTimer: QTimer can only be used with threads started with QThread
```
message in the server stdout.

**Comment by adrg** [comment]
For usage inside `goroutines` see the [Basic web page to PDF conversion server](https://github.com/adrg/go-wkhtmltopdf/blob/master/examples/http-server) or the [Configurable web page to PDF conversion server](https://github.com/adrg/go-wkhtmltopdf/blob/master/examples/http-server-advanced) examples. Issue https://github.com/adrg/go-wkhtmltopdf/issues/3 is also relevant.

The library must be initialized on the main thread and the conversion must be performed on the main thread as well. This is a known limitation of `wkhtmltox`, not of this package.

**Comment by zbykovskyi** [comment]
I suppose, as mentioned in previous comment, this code block 

```
func init() {
	// Set main function to run on the main thread.
	runtime.LockOSThread()
}

```
in general cases prevents situation with library stuck

**Comment by adrg** [comment]
Closing this issues as it has been addressed. Please reopen if necessary.
