### ISSUE TITLE
Compatibility: Signal Handling

### ISSUE THREAD

**Issue by MicahParks** [adrg/go-wkhtmltopdf#53]
I appear to have found an issue with my project where a panic arose when using this project and [`exec.Command`](https://pkg.go.dev/os/exec#Command) at the same time.

```
signal 17 received but handler not on signal stack
mp.gsignal stack [0xc000008000 0xc000010000], mp.g0 stack [0x7ffd1cc50000 0x7ffd1d44e2e0], sp=0xc0000a4bf8
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
```

I included code to reproduce this error below.

Unfortunately, I do not know much about programming in C. During troubleshooting, I saw a potential option may be to "wrap and mask" `wkhtmltox`'s signal handing. Is that within the scope of this project?

If not, I think an alternate option would be to create a separate service to interact with `wkhtmltox`, but I'd like to explore options that keep the library integrated first.

```go
package main

import (
	"bytes"
	"log"
	"os/exec"
	"runtime"

	pdf "github.com/adrg/go-wkhtmltopdf"
)

func init() {
	runtime.LockOSThread()
}

func main() {
	err := pdf.Init()
	if err != nil {
		log.Fatalf("Failed to initialize wkhtmltopdf: %v", err)
	}
	defer pdf.Destroy()

	println(getUname())
}

// This function is from Stripe's Golang SDK.
// https://github.com/stripe/stripe-go/blob/59660edfeed1968c8db9d6cae5e0e0bf0a93f9fe/stripe.go#L1503-L1522
func getUname() string {
	path, err := exec.LookPath("uname")
	if err != nil {
		return "unknown"
	}

	cmd := exec.Command(path, "-a")
	var out bytes.Buffer
	cmd.Stderr = nil // goes to os.DevNull
	cmd.Stdout = &out
	err = cmd.Run()
	if err != nil {
		return "unknown"
	}

	return out.String()
}
```

**Comment by adrg** [comment]
Hi @MicahParks,

This should work if you don't mind adding a bit of `C` code:
```go
package main

/*
#include <signal.h>

void update_sigchld_handler() {
	struct sigaction action;
	sigaction(SIGCHLD, NULL, &action);
	action.sa_flags = action.sa_flags | SA_ONSTACK;
	sigaction(SIGCHLD, &action, NULL);
}
*/
import "C"

import (
	"bytes"
	"log"
	"os/exec"
	"runtime"

	pdf "github.com/adrg/go-wkhtmltopdf"
)

func init() {
	runtime.LockOSThread()
}

func main() {
	err := pdf.Init()
	if err != nil {
		log.Fatalf("Failed to initialize wkhtmltopdf: %v", err)
	}
	defer pdf.Destroy()
	C.update_sigchld_handler()

	println(getUname())
}

// This function is from Stripe's Golang SDK.
// https://github.com/stripe/stripe-go/blob/59660edfeed1968c8db9d6cae5e0e0bf0a93f9fe/stripe.go#L1503-L1522
func getUname() string {
	path, err := exec.LookPath("uname")
	if err != nil {
		return "unknown"
	}

	cmd := exec.Command(path, "-a")
	var out bytes.Buffer
	cmd.Stderr = nil // goes to os.DevNull
	cmd.Stdout = &out
	err = cmd.Run()
	if err != nil {
		return "unknown"
	}

	return out.String()
}
```

It basically retrieves the signal handler for `SIGCHLD` (signal 17) and adds the `SA_ONSTACK` flag to it.

**Comment by MicahParks** [comment]
@adrg that does exactly what I need it to. Thank you!

This may benefit others working on projects similar to what I'm working on. Perhaps it would be good to include the function in this project and document it similar to main thread restriction.

**Comment by adrg** [comment]
@MicahParks I'm glad it works. I was actually not aware of this problem so thank you for pointing it out. I will probably add a `Known issues` section in the `README` and document both issues there.
