### ISSUE TITLE
Getting error on get the package

### ISSUE THREAD

**Issue by darmawan01** [adrg/go-wkhtmltopdf#8]
```
> go get github.com/adrg/go-wkhtmltopdf
go: finding github.com/adrg/go-wkhtmltopdf v0.2.2
go: downloading github.com/adrg/go-wkhtmltopdf v0.2.2
go: extracting github.com/adrg/go-wkhtmltopdf v0.2.2
# github.com/adrg/go-wkhtmltopdf
../../go/pkg/mod/github.com/adrg/go-wkhtmltopdf@v0.2.2/converter.go:7:10: fatal error: wkhtmltox/pdf.h: No such file or directory
 #include <wkhtmltox/pdf.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by adrg** [comment]
HI @darmawan01. What operating system are you on?  The `wkhtmltox` library needs to be installed and accessible in order to use the package.  See https://github.com/adrg/go-wkhtmltopdf#prerequisites.

**Comment by adrg** [comment]
@darmawan01 Did you manage to solve the issue by installing `wkhtmltox`? From the output you attached, I assume you are on Linux.

**Comment by darmawan01** [comment]
i use linux, i don't have installing `wkhtmltox`. ok i'll try to install it first

**Comment by adrg** [comment]
Closing. Please reopen if there are issues with the specified solution.
